### ISSUE TITLE
Cannot create feature requests

### ISSUE THREAD

**Issue by C2H6-383** [mokhosh/muddle#1]
### What happened?

I am unable to create feature request issues in this GitHub repository, as discussions seem to be disabled

### How to reproduce the bug

Go to issues in this GitHub repository. Try to create a new issue and select feature request. GitHub answers with a HTTP 404 because it seems to me that discussions are disabled in this repo. Therefore, feature requests are not available.

### Package Version

3.0

### PHP Version

8.3

### Laravel Version

11.0

### Which operating systems does with happen with?

Windows

### Notes

Thanks for this awesome package and for your help.

Feel free to request more information about this problem.

**Comment by mokhosh** [comment]
Thanks. Fixed.
